"""Tests for cycle advise preparation and execution backend."""

from __future__ import annotations

import json
from pathlib import Path

from devloop.cycle_advise import SEVERITY_ERROR, run_cycle_advise


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _files_snapshot(root: Path) -> set[str]:
    return {str(p.relative_to(root)) for p in root.rglob("*")}


def _errors(result) -> list[str]:
    return [item.message for item in result.findings if item.severity == SEVERITY_ERROR]


def _valid_models_yaml(policy_allowed: bool = True) -> str:
    allowed = "true" if policy_allowed else "false"
    return f"""\
schema_version: 1
policy:
  model_calls_allowed: {allowed}
providers:
  local_vllm:
    type: openai_compatible
    base_url: http://localhost:8000/v1
    api_key:
      mode: none
models:
  qwen3_local:
    name: qwen3_local_backend
    provider: local_vllm
roles:
  supervisor:
    model: qwen3_local
  reviewer:
    model: qwen3_local
"""


def _make_cycle(tmp_path: Path, cycle_id: str = "c-001") -> None:
    cycle_dir = tmp_path / ".ai-loop/cycles" / cycle_id
    _write(
        cycle_dir / "meta.yaml",
        f"schema_version: '0'\ncycle_id: {cycle_id}\ncreated_at: '2026-05-28'\nstatus: planned\n",
    )
    _write(cycle_dir / "task.md", "task\n")
    _write(cycle_dir / "report.md", "report\n")


def test_cycle_advise_executes_successfully_with_fake_transport(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _write(tmp_path / ".ai-loop/project.md", "project\n")
    _make_cycle(tmp_path, "c-001")
    _write(tmp_path / ".ai-loop/cycles/c-001/prompt.md", "prompt\n")

    def _fake_transport(url, payload, headers, timeout_seconds):
        assert url == "http://localhost:8000/v1/chat/completions"
        assert payload["model"] == "qwen3_local_backend"
        assert payload["temperature"] == 0
        assert isinstance(payload["messages"], list)
        assert len(payload["messages"]) == 2
        assert payload["messages"][0]["role"] == "system"
        assert payload["messages"][1]["role"] == "user"
        system_content = payload["messages"][0]["content"]
        user_content = payload["messages"][1]["content"]
        assert "spec-devloop" in system_content
        assert "canonical project state directory is `.ai-loop`" in system_content
        assert "Do not invent missing files" in system_content
        assert "Recommended next microtask" in system_content
        assert "allowlisted cycle artifacts" in system_content
        assert "python3 -m pytest -q" in system_content
        assert "do not recommend external tools" in system_content
        assert "--write-report" in system_content
        assert "writes only `.ai-loop/cycles/<cycle-id>/advisory.md`" in system_content
        assert "does not write or update `report.md`" in system_content
        assert "`plan.md`, `prompt.md`, and `summary.md` are optional context artifacts" in system_content
        assert "do not automatically classify readiness as low only because optional artifacts are missing" in system_content
        assert "minimal artifact set such as `meta.yaml`, `task.md`, and `report.md` may be sufficient" in system_content
        assert "canonical_project_state: .ai-loop" in user_content
        assert "allowed_cycle_artifacts: meta.yaml; task.md; plan.md; prompt.md; summary.md; report.md" in user_content
        assert "optional_cycle_artifacts: plan.md; prompt.md; summary.md" in user_content
        assert "absence alone does not imply low readiness" in user_content
        assert "minimal_validation_cycle_example: meta.yaml; task.md; report.md" in user_content
        assert "advisory_persistence_contract: --write-report writes only .ai-loop/cycles/<cycle-id>/advisory.md" in user_content
        assert "advisory_persistence_contract: --write-report does not write or update report.md" in user_content
        assert "cycle_advise_mutation_contract: cycle advise does not generate or update plan.md; prompt.md; summary.md; report.md" in user_content
        assert "artifact_distinction: report.md is a normal cycle artifact; advisory.md is the persisted model advisory generated by --write-report" in user_content
        assert "validation_command_guidance:" in user_content
        assert "grounding: use only the artifacts listed below" in user_content
        assert headers["Content-Type"] == "application/json"
        assert "Authorization" not in headers
        assert timeout_seconds == 15
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"- Keep scope focused."}}]}'

    result = run_cycle_advise(
        tmp_path,
        cycle_id="c-001",
        role="supervisor",
        allow_call=True,
        transport=_fake_transport,
    )

    assert result.ok is True
    assert result.attempted_transport is True
    assert result.prepared is not None
    assert result.execution is not None
    assert result.execution.ok is True
    assert result.execution.transport == "ok"
    assert result.execution.advisory_text == "- Keep scope focused."
    assert result.prepared.cycle_id == "c-001"
    assert result.prepared.role == "supervisor"
    assert result.prepared.resolved_model_key == "qwen3_local"
    assert result.prepared.backend_model_name == "qwen3_local_backend"
    assert result.prepared.provider_key == "local_vllm"
    assert ".ai-loop/project.md" in result.prepared.input_artifacts
    assert ".ai-loop/cycles/c-001/meta.yaml" in result.prepared.input_artifacts
    assert ".ai-loop/cycles/c-001/task.md" in result.prepared.input_artifacts
    assert ".ai-loop/cycles/c-001/prompt.md" in result.prepared.input_artifacts


def test_cycle_advise_transport_payload_shape_with_required_api_key(tmp_path: Path) -> None:
    _write(
        tmp_path / ".ai-loop/config/models.yaml",
        _valid_models_yaml(policy_allowed=True).replace(
            "mode: none",
            "mode: required\n      env: OPENAI_API_KEY",
        ),
    )
    _make_cycle(tmp_path, "c-001")
    captured: dict[str, object] = {}
    secret = "top-secret-token"

    def _fake_transport(url, payload, headers, timeout_seconds):
        captured["url"] = url
        captured["payload"] = payload
        captured["headers"] = dict(headers)
        captured["timeout"] = timeout_seconds
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"advisory text"}}]}'

    result = run_cycle_advise(
        tmp_path,
        cycle_id="c-001",
        role="supervisor",
        allow_call=True,
        environ={"OPENAI_API_KEY": secret},
        transport=_fake_transport,
    )

    assert result.ok is True
    assert result.prepared is not None
    assert result.prepared.auth_present is True
    assert captured["url"] == "http://localhost:8000/v1/chat/completions"
    assert "model" in captured["payload"]
    assert "messages" in captured["payload"]
    assert "Authorization" in captured["headers"]
    assert secret in captured["headers"]["Authorization"]
    assert secret not in " ".join(item.message for item in result.findings)


def test_cycle_advise_blocks_when_allow_call_missing(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _make_cycle(tmp_path, "c-001")
    attempted = {"value": False}

    def _fake_transport(*_args):
        attempted["value"] = True
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"x"}}]}'

    result = run_cycle_advise(tmp_path, cycle_id="c-001", allow_call=False, transport=_fake_transport)

    assert result.ok is False
    assert result.attempted_transport is False
    assert attempted["value"] is False
    assert any("allow_call=True" in message for message in _errors(result))


def test_cycle_advise_blocks_when_policy_false(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=False))
    _make_cycle(tmp_path, "c-001")
    attempted = {"value": False}

    def _fake_transport(*_args):
        attempted["value"] = True
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"x"}}]}'

    result = run_cycle_advise(tmp_path, cycle_id="c-001", allow_call=True, transport=_fake_transport)

    assert result.ok is False
    assert result.attempted_transport is False
    assert attempted["value"] is False
    assert any("policy.model_calls_allowed" in message for message in _errors(result))


def test_cycle_advise_fails_when_config_missing_or_invalid(tmp_path: Path) -> None:
    attempted = {"value": False}

    def _fake_transport(*_args):
        attempted["value"] = True
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"x"}}]}'

    missing = run_cycle_advise(tmp_path, cycle_id="c-001", allow_call=True, transport=_fake_transport)
    assert missing.ok is False
    assert missing.attempted_transport is False
    assert attempted["value"] is False
    assert any("model config file is required for cycle advise" in message for message in _errors(missing))

    _write(tmp_path / ".ai-loop/config/models.yaml", "schema_version: 2\n")
    invalid = run_cycle_advise(tmp_path, cycle_id="c-001", allow_call=True, transport=_fake_transport)
    assert invalid.ok is False
    assert invalid.attempted_transport is False
    assert attempted["value"] is False
    assert any("model config is invalid" in message for message in _errors(invalid))


def test_cycle_advise_unknown_role_fails_before_transport(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _make_cycle(tmp_path, "c-001")
    attempted = {"value": False}

    def _fake_transport(*_args):
        attempted["value"] = True
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"x"}}]}'

    result = run_cycle_advise(tmp_path, cycle_id="c-001", role="missing", allow_call=True, transport=_fake_transport)

    assert result.ok is False
    assert result.attempted_transport is False
    assert attempted["value"] is False
    assert any("unknown role: missing" in message for message in _errors(result))


def test_cycle_advise_missing_cycle_fails_before_transport(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    attempted = {"value": False}

    def _fake_transport(*_args):
        attempted["value"] = True
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"x"}}]}'

    result = run_cycle_advise(tmp_path, cycle_id="c-999", role="supervisor", allow_call=True, transport=_fake_transport)

    assert result.ok is False
    assert result.attempted_transport is False
    assert attempted["value"] is False
    assert any("cycle directory missing" in message for message in _errors(result))


def test_cycle_advise_runtime_failure_is_sanitized(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _make_cycle(tmp_path, "c-001")

    def _fake_transport(*_args):
        raise TimeoutError("secret-token")

    result = run_cycle_advise(tmp_path, cycle_id="c-001", role="reviewer", allow_call=True, transport=_fake_transport)

    assert result.ok is False
    assert result.attempted_transport is True
    assert result.execution is not None
    assert result.execution.transport == "error"
    assert result.execution.error_message == "transport request timed out"
    assert "secret-token" not in (result.execution.error_message or "")


def test_cycle_advise_invalid_model_response_fails(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _make_cycle(tmp_path, "c-001")

    def _fake_transport(*_args):
        return 200, b'{"choices":[{"message":{"role":"assistant"}}]}'

    result = run_cycle_advise(tmp_path, cycle_id="c-001", role="reviewer", allow_call=True, transport=_fake_transport)

    assert result.ok is False
    assert result.attempted_transport is True
    assert result.execution is not None
    assert result.execution.transport == "error"
    assert "assistant content" in (result.execution.error_message or "")


def test_cycle_advise_does_not_modify_files(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _make_cycle(tmp_path, "c-001")
    before = _files_snapshot(tmp_path)

    def _fake_transport(*_args):
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"all good"}}]}'

    result = run_cycle_advise(tmp_path, cycle_id="c-001", role="reviewer", allow_call=True, transport=_fake_transport)
    after = _files_snapshot(tmp_path)

    assert result.ok is True
    assert result.attempted_transport is True
    assert before == after


def test_cycle_advise_write_report_creates_advisory_file_only(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _make_cycle(tmp_path, "c-001")
    before = _files_snapshot(tmp_path)

    def _fake_transport(*_args):
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"safe advisory content"}}]}'

    result = run_cycle_advise(
        tmp_path,
        cycle_id="c-001",
        role="supervisor",
        allow_call=True,
        write_report=True,
        transport=_fake_transport,
    )
    after = _files_snapshot(tmp_path)

    assert result.ok is True
    assert result.execution is not None
    assert result.execution.advisory_text == "safe advisory content"
    assert result.report_written is True
    assert result.report_path == ".ai-loop/cycles/c-001/advisory.md"
    assert after - before == {".ai-loop/cycles/c-001/advisory.md"}


def test_cycle_advise_write_report_content_is_sanitized(tmp_path: Path) -> None:
    _write(
        tmp_path / ".ai-loop/config/models.yaml",
        _valid_models_yaml(policy_allowed=True).replace(
            "mode: none",
            "mode: required\n      env: OPENAI_API_KEY",
        ),
    )
    _write(tmp_path / ".ai-loop/project.md", "project context\n")
    _make_cycle(tmp_path, "c-001")
    _write(tmp_path / ".ai-loop/cycles/c-001/summary.md", "summary context\n")
    secret = "secret-token-123"

    def _fake_transport(*_args):
        body = {"choices": [{"message": {"role": "assistant", "content": "## Summary\nKeep scope tight."}}]}
        return 200, json.dumps(body).encode("utf-8")

    result = run_cycle_advise(
        tmp_path,
        cycle_id="c-001",
        role="supervisor",
        allow_call=True,
        write_report=True,
        environ={"OPENAI_API_KEY": secret},
        transport=_fake_transport,
    )

    assert result.ok is True
    report_path = tmp_path / ".ai-loop/cycles/c-001/advisory.md"
    content = report_path.read_text(encoding="utf-8")
    assert "cycle id: c-001" in content
    assert "requested role: supervisor" in content
    assert "resolved model key: qwen3_local" in content
    assert "backend model name: qwen3_local_backend" in content
    assert "provider key: local_vllm" in content
    assert "input artifacts:" in content
    assert "transport status: ok" in content
    assert "generated_at_utc:" in content
    assert "no files were modified except the explicit report write" in content
    assert "## Summary\nKeep scope tight." in content
    assert secret not in content
    assert "Authorization" not in content
    assert '"messages"' not in content
    assert '"model"' not in content
    assert '"choices"' not in content


def test_cycle_advise_write_report_fails_when_file_exists(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _make_cycle(tmp_path, "c-001")
    report_path = tmp_path / ".ai-loop/cycles/c-001/advisory.md"
    _write(report_path, "existing content")
    attempted = {"value": False}

    def _fake_transport(*_args):
        attempted["value"] = True
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"new advisory"}}]}'

    result = run_cycle_advise(
        tmp_path,
        cycle_id="c-001",
        role="supervisor",
        allow_call=True,
        write_report=True,
        transport=_fake_transport,
    )

    assert result.ok is False
    assert result.attempted_transport is False
    assert result.execution is None
    assert result.report_written is False
    assert result.report_overwritten is False
    assert result.report_path == ".ai-loop/cycles/c-001/advisory.md"
    assert result.error_code == "report_exists"
    assert attempted["value"] is False
    assert report_path.read_text(encoding="utf-8") == "existing content"


def test_cycle_advise_write_report_not_written_on_preparation_or_execution_failure(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _make_cycle(tmp_path, "c-001")

    blocked = run_cycle_advise(tmp_path, cycle_id="c-001", allow_call=False, write_report=True)
    assert blocked.ok is False
    assert blocked.report_written is False
    assert blocked.report_overwritten is False
    assert not (tmp_path / ".ai-loop/cycles/c-001/advisory.md").exists()

    def _broken_transport(*_args):
        raise TimeoutError("token")

    runtime = run_cycle_advise(
        tmp_path,
        cycle_id="c-001",
        role="supervisor",
        allow_call=True,
        write_report=True,
        transport=_broken_transport,
    )
    assert runtime.ok is False
    assert runtime.report_written is False
    assert runtime.report_overwritten is False
    assert not (tmp_path / ".ai-loop/cycles/c-001/advisory.md").exists()


def test_cycle_advise_overwrite_report_requires_write_report(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _make_cycle(tmp_path, "c-001")
    attempted = {"value": False}

    def _fake_transport(*_args):
        attempted["value"] = True
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"new advisory"}}]}'

    result = run_cycle_advise(
        tmp_path,
        cycle_id="c-001",
        role="supervisor",
        allow_call=True,
        write_report=False,
        overwrite_report=True,
        transport=_fake_transport,
    )

    assert result.ok is False
    assert result.attempted_transport is False
    assert result.report_written is False
    assert result.report_overwritten is False
    assert attempted["value"] is False
    assert result.error_code is None
    assert any("--overwrite-report requires --write-report" in message for message in _errors(result))


def test_cycle_advise_write_report_overwrites_existing_file_when_enabled(tmp_path: Path) -> None:
    _write(tmp_path / ".ai-loop/config/models.yaml", _valid_models_yaml(policy_allowed=True))
    _make_cycle(tmp_path, "c-001")
    report_path = tmp_path / ".ai-loop/cycles/c-001/advisory.md"
    _write(report_path, "existing content")
    attempted = {"value": False}

    def _fake_transport(*_args):
        attempted["value"] = True
        return 200, b'{"choices":[{"message":{"role":"assistant","content":"overwritten advisory"}}]}'

    result = run_cycle_advise(
        tmp_path,
        cycle_id="c-001",
        role="supervisor",
        allow_call=True,
        write_report=True,
        overwrite_report=True,
        transport=_fake_transport,
    )

    assert result.ok is True
    assert result.attempted_transport is True
    assert result.report_written is True
    assert result.report_overwritten is True
    assert result.report_path == ".ai-loop/cycles/c-001/advisory.md"
    assert attempted["value"] is True
    assert "overwritten advisory" in report_path.read_text(encoding="utf-8")
